# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PopupController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopupController

	pod 'PopupController', :git => 'https://github.com/ahmedsafadii/PopupController.git'

  target 'PopupControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
